### ISSUE TITLE
Not drawing

### ISSUE THREAD

**Issue by Cool-ShowTTV** [ipodtouch0218/JackboxDrawer#3]
When I click export to game its not drawing its just submitting the blank shirt and nothing else

game: T.K.O.

**Comment by Cool-ShowTTV** [comment]
and yes i have the java file and newest files

**Comment by ipodtouch0218** [comment]
Confirmed & fixed in Release 1.4.2.

**Comment by anytarseir67** [comment]
> Confirmed & fixed in Release 1.4.2.

no you didn't... it's just as broken as before

**Comment by ipodtouch0218** [comment]
> 
> 
> > Confirmed & fixed in Release 1.4.2.
> 
> no you didn't... it's just as broken as before

This was over 15 days ago. If it's broken again, please tell me the game / guarantee your script and jar are on the latest version like this: https://i.vgy.me/nxvUfK.gif

**Comment by rosygoldmoth** [comment]
i dont have the extension how do i get it
