### ISSUE TITLE
Add an open-source licence

### ISSUE THREAD

**Issue by fffelix-jan** [ipodtouch0218/JackboxDrawer#4]
Please add a licence such as the MIT, GPL, etc. so we are legally allowed to modify and share the code. Thanks!

**Comment by fffelix-jan** [comment]
Nevermind, I found the MIT licence in one of the directories, but may you also put a copy in the root directory so it's easier to find? Thanks!

**Comment by ipodtouch0218** [comment]
> 
> 
> Nevermind, I found the MIT licence in one of the directories, but may you also put a copy in the root directory so it's easier to find? Thanks!

That MIT license is actually for the teenyicons that I used, but I added an MIT license to the base directory of my own.
