### ISSUE TITLE
Feature Request: Patently Stupid

### ISSUE THREAD

**Issue by drewbitt** [ipodtouch0218/JackboxDrawer#6]

**Comment by ipodtouch0218** [comment]
Patently stupid is planned to have support, it'll be added once I get done with my finals week.

**Comment by ipodtouch0218** [comment]
Bad news, patently stupid is not possible due to them validating color on the server-side (aka, custom colors don't work, making imported images impossible)

They have also made this change to drawful 2, and I'm starting to worry they will continue to patch games in the future.
